### ISSUE TITLE
Could we please get infinite scrolling? 🙏

### ISSUE THREAD

**Issue by mbi** [avadhesh18/rdx#2]
I.e. fetch and append the content of the next page when you reach the bottom.

**Comment by avadhesh18** [comment]
Tonight or tomorrow probably.

**Comment by avadhesh18** [comment]
Done ✅

**Comment by mbi** [comment]
Thank you! Did a quick test and it doesn't seem to work for me, though. It just reaches the end of the page and nothing happens, no Javascript errors, nothing.
Tested [here](https://rdx.overdevs.com/) and on my fork, in iOS and Firefox.

**Comment by avadhesh18** [comment]
That's strange, works on every browser I was able to physically check(chrome on Mac, chrome on Android, Firefox on Mac, iOS safari, iOS webapp, Win10 chrome). Can you try loading rdx.overdevs.com in your browser then go to settings and enable infinite scrolling and then refresh the home page.

**Comment by mbi** [comment]
Oh, you have to enable the feature! I assumed it was just on by default. After toggling it works like a charm!

awesome thank you!🙏
